### ISSUE TITLE
Shared channels with startup detroit

### ISSUE THREAD

**Issue by sampl** [MadeInA2/madeina2#112]
@shriyash said:

> Hey Sam! I talked to @jshwlkr and he suggested I reach out to you
> Do you help manage / admin this slack group?
> I run a similar open-source project & slack group for Detroit (http://startupdetroit.co)
> Slack recently added the "shared channels" feature and I think it'd be a great way to bring the Ann Arbor and Detroit startup communities closer together to make a shared channel between our groups (#detroitXannarbor or something)
> https://get.slack.help/hc/en-us/articles/360035092414-Create-shared-channels (edited) 
> any thoughts?

**Comment by sampl** [comment]
I'll have to look into shared channels, don't know how they work. I'm open to sharing as a general principle, but also recognize that the "single a2 detroit tech community" is kind of a myth and each has their own identity

**Comment by jshwlkr** [comment]
That's actually a good point that I hadn't considered. I'm open to a relationship and bringing these communities closer together but I'd be cautious about prescribing what that relationship might be and with what ease it could/would take to maintain it.

**Comment by sampl** [comment]
Just checked out shared channels, seems pretty straightforward. I’d be down.

Except that we need a paid plan and we’re on the slack free tier iirc :(

**Comment by jshwlkr** [comment]
~$6 a person.... that seems like a notable hurdle to some of the things we're trying to do. I don't think I'm particular interested in requiring a fee from people to join, what would probably seem like, the inner circle.

**Comment by briankelly** [comment]
Shared channels are only available for paid slack plans ([reference](https://slackhq.com/slack-shared-channels)).
> It’s officially out of beta today and available for all paid plans.

I agree with what @sampl said.
>  I'm open to sharing as a general principle, but also recognize that the "single a2 detroit tech community" is kind of a myth and each has their own identity

Happy to support / collaborate / trade notes with any folks—especially Michigan and neighboring tech communities—but I also think it's important for each community to focus their energy in supporting the folks already in their community. If nothing else than for convenience and all the good that comes by being able to collaborate in person.

**Comment by shriyash** [comment]
Definitely agree with a lot of what's being discussed here! I must have misread that part about it only being available for paid plans.

Thanks for the consideration :)

**Comment by sampl** [comment]
Alright yall thanks for the great comments here, closing this for now
