### ISSUE TITLE
Add Cronicle

### ISSUE THREAD

**Issue by sampl** [MadeInA2/madeina2#114]
https://cronicle.press/

New publication, but useful for our goal of sharing the tech scene. Thoughts @jshwlkr or anyone else on how to add this? Maybe it's finally time for a redesign...

**Comment by jshwlkr** [comment]
I think we could slip this in to community for the moment, until we have a better handle on how we might categorize these things. (Concentrate might also be a candidate.)

**Comment by sampl** [comment]
dun 1df141de9cfd9aaaabb4b46c662ea3ef708ce4e3
