### ISSUE TITLE
When are site updates / deployments performed?

### ISSUE THREAD

**Issue by mattnedrich** [MadeInA2/madeina2#122]
Some merged PRs have yet to be deployed. Wondering how/when updates are deployed?

**Comment by jshwlkr** [comment]
Intermittently, depending on how much is waiting to be deployed and what kinds of things are changing. I'll try to make a deploy this week sometime, this weekend at the latest. (I'd like to make a deployment today sometime if I can.)

**Comment by sampl** [comment]
I've been meaning to use Vue or React or something front-end heavy, simply
because if we don't have a local compile step than we can just accept PRs
and the site should be updated (its hosted on github pages)
