### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by sampl** [MadeInA2/madeina2#14]

**Comment by JangoSteve** [comment]
Any update on this? I was going to clone the site for a small community project, but I'm not sure what the license is. Without one, it defaults to all rights reserved, so cloning is a no-go. Please let us know. Would love if this turned out to be MIT licensed or similar.

**Comment by sampl** [comment]
I'm down to license it, maybe something creative commons, ie commercial w/ attribution? Thoughts @jamor @jshwlkr ?

**Comment by jshwlkr** [comment]
Yeah, I wouldn't hate the attribution. Would we extend this to include both the site, it's build process, and any json/api we serve?

**Comment by sampl** [comment]
I was just talking about this in the slack channel--maybe a separate
license for the json content of the companies etc? Actually yeah maybe it's
just the same thing. Copy what you want with attribution...

**Comment by sampl** [comment]
Apparently creative Commons licenses are not for software. If we want
attribution we should probably use GNU which requires using the same
license for derivatives. If you don’t want that the option originally
mentioned (MIT? I think, I’m in my email) is fine.

**Comment by jshwlkr** [comment]
Which GNU flavor?

**Comment by JangoSteve** [comment]
One of the advantages of choosing an established/popular license is that people will tend to know it without reading it, so ubiquity tends to be an advantage.

For GNU, GPL is the most well known, and for GPL, you'd probably want AGPL, since most of the other GPL flavors (GPL v3, LGPL, etc.) are written primarily with distributive software in mind. AGPL is adapted for software that you copy and host on a server for others to access instead of packaging up for distribution to others.

**Comment by sampl** [comment]
Thank you Steve. Any objections to AGPL?

**Comment by jshwlkr** [comment]
I believe that means anyone using resources from madeina2 must license and distribute their product with an AGPL license as well. I'm fine with that if everyone else is. (Though, to be honest, how would we prove someone's violating the license?)

**Comment by sampl** [comment]
Yeah that’s true, on second thought probably not useful if we want to let
others groups use the list.

OK how about:
- the code is MIT license
- soon, we split out the list of companies/groups etc from the code into a
json file
- that file will be licensed with a Creative Commons commercial sharealike

**Comment by jshwlkr** [comment]
That sounds good.

**Comment by sampl** [comment]
Added
