### ISSUE TITLE
madeina2.com isn't loading - halp!

### ISSUE THREAD

**Issue by steiza** [MadeInA2/madeina2#59]
When I visit madeina2.com, I get a 404 page:

<img width="1262" alt="screen shot 2017-06-16 at 5 22 14 pm" src="https://user-images.githubusercontent.com/167759/27245261-6b05add4-52b8-11e7-99b4-213d581911c3.png">

I thought madeina2.com was using GitHub pages, and I could fix it in a pull request, but it seems like it's actually running in Heroku, so we might need someone who has access to that.

**Comment by jshwlkr** [comment]
It was a CNAME issue. (When in doubt, it's always a CNAME issue.)
