### ISSUE TITLE
Hook Logic acquired

### ISSUE THREAD

**Issue by jshwlkr** [MadeInA2/madeina2#85]
Hook Logic has been acquired by Criteo. I'm not entirely sure what we should do with the link, as the site is gone.

**Comment by sampl** [comment]
Changed the name to Criteo for now, though we'll need to re-evaluate our rules around having the HQ in Ann Arbor

https://github.com/MadeInA2/madeina2/commit/9519c086b0b422aadb8af8efce06699152c8c6f0
